apiVersion: batch/v1
kind: Job
metadata:
  name: guidedpath-migration
spec:
  template:
    spec:
      containers:
      - name: migration
        image: ghcr.io/genewang/guidedpath/backend:latest
        command: ["python", "-m", "alembic", "upgrade", "head"]
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: guidedpath-secrets
              key: database-url
      restartPolicy: OnFailure
