apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: guidedpath-platform

resources:
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - ingress.yaml

images:
  - name: ghcr.io/genewang/guidedpath/backend
    newTag: latest
  - name: ghcr.io/genewang/guidedpath/frontend
    newTag: latest

namespace: guidedpath

commonLabels:
  app: guidedpath
  managed-by: kustomize
